name: sample-contract

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sample-contract:
    name: sample-contract
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run synthetic contract tests
        run: python -m unittest discover
